//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace The_Testo.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compound
    {
        public int CompID { get; set; }
        public int TechID { get; set; }
        public int ProductID { get; set; }
        public int DishID { get; set; }
        public double Value { get; set; }
        public int UnitID { get; set; }
    
        public virtual TechnologyCard TechnologyCard { get; set; }
        public virtual Product Product { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
