//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace The_Testo.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ordered_dishes
    {
        public int OrderedDishID { get; set; }
        public int DishID { get; set; }
        public int DishAmount { get; set; }
        public int OrderID { get; set; }
        public System.DateTime OrderDate { get; set; }
    
        public virtual Dish Dish { get; set; }
        public virtual Order Order { get; set; }
    }
}
