//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace The_Testo.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TechnologyCard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TechnologyCard()
        {
            this.Compound = new HashSet<Compound>();
        }
    
        public int TechID { get; set; }
        public int DishID { get; set; }
        public string DishRecipe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Compound> Compound { get; set; }
        public virtual Dish Dish { get; set; }
    }
}
